version: "3.8"

services:

  accounts:
    image: eazybytes/accounts
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - eazybank-network
      
  loans:
    image: eazybytes/loans
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - eazybank-network
      
  cards:
    image: eazybytes/cards
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - eazybank-network
 
networks:
  eazybank-network: